### ISSUE TITLE
Map of Trails

### ISSUE THREAD

**Issue by sxzrmn** [Ammani-hash/Team1GreatOutdoors#23]
Maps of three trails

- [x] Rattlesnake Ledge Trail

- [x] Skyline Loop

- [x] Mount Storm King

**Comment by Ilikemyhome** [comment]
Rattlesnake -[StrollingtheRattlesnakeLakeRecreationArea.pdf](https://github.com/user-attachments/files/17967612/StrollingtheRattlesnakeLakeRecreationArea.pdf)

![Image](https://github.com/user-attachments/assets/f1a4ef0c-7404-4bae-ade7-868deaaef8b3)

**Comment by Ilikemyhome** [comment]
Skyline loop trail
![Image](https://github.com/user-attachments/assets/4d3c223b-262c-4d2f-a605-29115e0f465d)

**Comment by Ilikemyhome** [comment]
Mount storm King-![Image](https://github.com/user-attachments/assets/d2fbeb8a-20be-40ec-920b-6929867bd171)
